platform :osx, '26.4'

target 'MarkdownEditor' do
  pod 'GCDWebServer', :inhibit_warnings => true

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '26.4'
    end
  end
end
