platform :osx, '26.3'

target 'MarkdownEditor' do
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '26.3'
    end
  end
end
